# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(376, 248)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("font: 75 12pt \"Arial\";\n"
"color: rgb(40, 160, 80);\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBoxFreq = QtWidgets.QGroupBox(Form)
        self.groupBoxFreq.setStyleSheet("")
        self.groupBoxFreq.setObjectName("groupBoxFreq")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxFreq)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.doubleSpinBoxFreq = QtWidgets.QDoubleSpinBox(self.groupBoxFreq)
        self.doubleSpinBoxFreq.setStyleSheet("color: rgb(160, 140, 0);")
        self.doubleSpinBoxFreq.setDecimals(1)
        self.doubleSpinBoxFreq.setMinimum(76.0)
        self.doubleSpinBoxFreq.setMaximum(108.0)
        self.doubleSpinBoxFreq.setSingleStep(0.1)
        self.doubleSpinBoxFreq.setProperty("value", 76.0)
        self.doubleSpinBoxFreq.setObjectName("doubleSpinBoxFreq")
        self.verticalLayout_2.addWidget(self.doubleSpinBoxFreq)
        self.horizontalLayout.addWidget(self.groupBoxFreq)
        self.groupBoxPow = QtWidgets.QGroupBox(Form)
        self.groupBoxPow.setObjectName("groupBoxPow")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxPow)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.doubleSpinBoxPow = QtWidgets.QDoubleSpinBox(self.groupBoxPow)
        self.doubleSpinBoxPow.setStyleSheet("color: rgb(160, 140, 0);")
        self.doubleSpinBoxPow.setDecimals(0)
        self.doubleSpinBoxPow.setProperty("value", 100.0)
        self.doubleSpinBoxPow.setObjectName("doubleSpinBoxPow")
        self.verticalLayout_3.addWidget(self.doubleSpinBoxPow)
        self.horizontalLayout.addWidget(self.groupBoxPow)
        self.groupBoxTemp = QtWidgets.QGroupBox(Form)
        self.groupBoxTemp.setStyleSheet("")
        self.groupBoxTemp.setObjectName("groupBoxTemp")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBoxTemp)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelTemp = QtWidgets.QLabel(self.groupBoxTemp)
        self.labelTemp.setStyleSheet("color: rgb(160, 140, 0);")
        self.labelTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTemp.setObjectName("labelTemp")
        self.verticalLayout_4.addWidget(self.labelTemp)
        self.horizontalLayout.addWidget(self.groupBoxTemp)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBoxRds = QtWidgets.QGroupBox(Form)
        self.groupBoxRds.setObjectName("groupBoxRds")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBoxRds)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEditRds = QtWidgets.QLineEdit(self.groupBoxRds)
        self.lineEditRds.setStyleSheet("color: rgb(160, 140, 0);")
        self.lineEditRds.setObjectName("lineEditRds")
        self.horizontalLayout_6.addWidget(self.lineEditRds)
        self.pushButtonRds = QtWidgets.QPushButton(self.groupBoxRds)
        self.pushButtonRds.setStyleSheet("color: rgb(255, 70, 200);")
        self.pushButtonRds.setObjectName("pushButtonRds")
        self.horizontalLayout_6.addWidget(self.pushButtonRds)
        self.horizontalLayout_2.addWidget(self.groupBoxRds)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBoxTerminal = QtWidgets.QGroupBox(Form)
        self.groupBoxTerminal.setObjectName("groupBoxTerminal")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBoxTerminal)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEditTerminal = QtWidgets.QLineEdit(self.groupBoxTerminal)
        self.lineEditTerminal.setStyleSheet("color: rgb(160, 140, 0);")
        self.lineEditTerminal.setObjectName("lineEditTerminal")
        self.horizontalLayout_7.addWidget(self.lineEditTerminal)
        self.pushButtonTerminal = QtWidgets.QPushButton(self.groupBoxTerminal)
        self.pushButtonTerminal.setStyleSheet("color: rgb(255, 70, 200);")
        self.pushButtonTerminal.setObjectName("pushButtonTerminal")
        self.horizontalLayout_7.addWidget(self.pushButtonTerminal)
        self.horizontalLayout_4.addWidget(self.groupBoxTerminal)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.labelStatus = QtWidgets.QLabel(Form)
        self.labelStatus.setStyleSheet("color: rgb(160, 140, 0);")
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout.addWidget(self.labelStatus)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "FM"))
        self.groupBoxFreq.setTitle(_translate("Form", "Frequency, MHz"))
        self.groupBoxPow.setTitle(_translate("Form", "Power, %"))
        self.groupBoxTemp.setTitle(_translate("Form", "Temperature, C"))
        self.labelTemp.setText(_translate("Form", "t"))
        self.groupBoxRds.setTitle(_translate("Form", "RDS"))
        self.lineEditRds.setText(_translate("Form", "TEXT"))
        self.pushButtonRds.setText(_translate("Form", "SET RDS"))
        self.groupBoxTerminal.setTitle(_translate("Form", "Terminal"))
        self.pushButtonTerminal.setText(_translate("Form", "SEND"))
        self.labelStatus.setText(_translate("Form", "status"))
